# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [13]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

bmi = np.array(weight) / (np.array(height)**2) * 730
for i in bmi:
    print("BMI is: {}{}".format(round(i, 2), "%"))

BMI is: 16.87%
BMI is: 17.88%
BMI is: 18.83%
BMI is: 19.71%
BMI is: 20.55%
BMI is: 21.33%
BMI is: 22.06%


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [18]:
def random_matrix(num1, num2, shape, datatype):
  matrix = np.random.uniform(num1, num2, shape)
  return matrix.astype(datatype)


print("Here is a random matrix: \n", random_matrix(1, 10, (5, 5), int))
print("Here is another random matrix: \n", random_matrix(8, 15, (4, 5), float))


Here is a random matrix: 
 [[5 1 7 9 8]
 [9 8 7 3 3]
 [2 7 4 8 3]
 [8 7 4 7 7]
 [4 1 7 5 7]]
Here is another random matrix: 
 [[13.25331867 14.23090624 10.57193826 10.90864603 12.76583446]
 [ 9.74492296 11.11623653  9.04512022 11.99963135 11.84644357]
 [12.46694866 12.77043025 14.60510613  9.81867861 13.83227258]
 [11.58251078 13.9404672   9.13791808 10.34730248 12.04642821]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [60]:
import csv
import numpy as np

In [59]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray


def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

slugging2017 = sum(bs2017['SLG'])/len(bs2017['SLG'])
slugging2018 = sum(bs2018['SLG'])/len(bs2018['SLG'])

# SLG in 2017 vs 2018
print('Average SLG for Red Sox in 2017: {}'.format(round(slugging2017 ,3)))
print('Average SLG for Red Sox in 2018: {}'.format(round(slugging2018 ,3)))

difference = abs((round(slugging2017, 3))-(round(slugging2018, 3)))

print('\nOverall, the difference in SLG between the two seasons is: {}'.format(round(difference, 5)))

# Total Hits
# total_hits = sum(bs2018['H'])
# print("\n Total Hits: {}".format(total_hits))

# # Home Runs Total
# total_HR = sum(bs2018['HR'])
# print('\n Total Home Runs in 2018: {}'.format(total_HR))


Average SLG for Red Sox in 2017: 0.393
Average SLG for Red Sox in 2018: 0.388

Overall, the difference in SLG between the two seasons is: 0.005
